# Generated by Django 4.1 on 2022-09-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_avatar_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sessionyearmodel',
            name='user',
        ),
    ]
